### ISSUE TITLE
KeyError on running program

### ISSUE THREAD

**Issue by anovicecodemonkey** [digsim/missingTvShows#3]
```bash 
python --version
```
Python 3.4.2

and 

```bash 
python2 --version
```
Python 2.7.9

OS: Arch Linux

```python
$ python missing_tvshows.py


[=========                                                                                           ] 8%Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pytvdbapi/api.py", line 192, in __getitem__
    return self.seasons[item]
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "missing_tvshows.py", line 323, in <module>
    sms.getArguments(sys.argv[1:])
  File "missing_tvshows.py", line 299, in getArguments
    self.main()
  File "missing_tvshows.py", line 282, in main
    unwatched_finished_shows,  unwatched_unfinished_shows,  watchedsome_unfinished_shows,  watchedsome_finished_shows = self.getSeriesInformation()
  File "missing_tvshows.py", line 176, in getSeriesInformation
    number_of_episodes = self.getTotalNumberOfEpisodes(int(rowId),  int(rowSeason))
  File "missing_tvshows.py", line 111, in getTotalNumberOfEpisodes
    number_of_episodes = len(show[season])
  File "/usr/lib/python3.4/site-packages/pytvdbapi/api.py", line 194, in __getitem__
    raise error.TVDBIndexError(u"Season {0} not found".format(item))
pytvdbapi.error.TVDBIndexError: ('Season 3 not found', (), {})`
```

**Comment by digsim** [comment]
Can you try executing
```bash
python2 missing_tvshows.py
```
to check whether the problem is python3 related or not?

**Comment by digsim** [comment]
Maybe the tvshow.log file gives a hint. I don't understand how line can raise a pytvdbapi error since this line is just checking the length of an array. Can you provide the interesting part of  the tvshow.log file?

**Comment by anovicecodemonkey** [comment]
The same error presents when using Python 2 as well. 

The debug doesn't appear to contain any errors. I have worked out what is causing the error though, I had files for a different show placed in the wrong folder and because of this, Kodi scanned them as season 3 of that folders' show but no third season exists for the real show.

**Comment by digsim** [comment]
Ok I see. Since the show is removed from Kodi  the script should not try anymore to fetch information about this show. The tvdbdb.db only serves as cache. Thus, it shouldn't matter what this file contains. However, it definitely doesn't harm to remove it and have it recreated after such problems. 

Yet, that makes it difficult to provide help. Can you check the log file to see which show the application is working on when the error happens? There you should find the series id and the season number the script is working on. You should find a line like
```bash
[DEBUG     ] 12/03/2015 16:51:13  missing_tvshows: 175 getSeriesInformation Currently treating series Chuck with id: 80348 and Season 1
```

Then you can check with thetvdb.com website. -> http://thetvdb.com/?tab=series&id=80348 where you replace the last part with the series id of the debug log.

**Comment by anovicecodemonkey** [comment]
It's http://thetvdb.com/?tab=series&id=253350. 

I can re-add the show if needed for debugging I just removed it to test if the error went away. The show is definitely not showing up in the Kodi program anymore but even after deleting the files mentioned, it still tries to fetch the information and errors out. 

So, steps to reproduce: 
1. Make a folder with the show name. 
2. Place a few files for another show with a higher season count than the show in question.
3. Scan the folder into the library, ensuring the 3rd season is detected as belonging to the show.
4. Run missing_tvshows.py and you will get the error.

**Comment by digsim** [comment]
I tried to reproduce the issue. For now I'm having trouble to get the same results as you get. 
With a fresh system and Kodi, I created following folder structure:
```
ruppena@fernsehen:~$ ll -R Series/
total 0
drwxr-xr-x  5 ruppena  staff   170B Mar 13 08:07 Anger Management/

Series//Anger Management:
total 0
drwxr-xr-x  4 ruppena  staff   136B Mar 13 16:44 Season 1/
drwxr-xr-x  4 ruppena  staff   136B Mar 13 16:44 Season 2/
drwxr-xr-x  4 ruppena  staff   136B Mar 13 16:45 Season 3/

Series//Anger Management/Season 1:
total 0
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:44 Anger Management S01E1.mkv
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:44 Anger Management S01E2.mkv

Series//Anger Management/Season 2:
total 0
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:44 Anger Management S02E1.mkv
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:44 Anger Management S02E2.mkv

Series//Anger Management/Season 3:
total 0
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:45 Chuck - S03E1.mkv
-rw-r--r--  1 ruppena  staff     0B Mar 13 16:45 Chuck - S03E2.mkv
```
Then I defined the folder Series as my series folder in Kodi and did a scan. Kodi finds the Anger Managment with seasons 1 and 2 but completely ignores the two episodes of Chuck. Of course, when I launch the script now, everything is fine.

How do you manage to get Kodi recognise a foreign series in this folder structure?
